name: morning
on:
  schedule:
  - cron:  '40 7 * * 1,2,3,4,5,6' # week up 1~6
  - cron:  '0 8 * * 1,2,3,4,5,6' # morning start 1~6
  - cron:  '0 11 * * 1,2,3,4,5,6' # moon 1~6
  - cron:  '0 13 * * 1,2,3,4,5,6'  # moon week up 1~6
  - cron:  '0 16 * * 1,2,3,4,5,6'  # sport 1~6
  - cron:  '30 16 * * 1,2,3,4,5,6' # sport end 1~6
  - cron:  '30 19 * * 1,2,3,4,5,6' # night start 1~6
  - cron:  '30 23 * * 1,2,3,4,5,6' # night end 1~6
  - cron:  '15 1 * * 1,2,3,4,5,6'  # sleep 1~6
  - cron:  '0 9 * * 0' # weekend
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send daily scheme
    steps:
      - name: sender on week up
        if: github.event.schedule == '40 7 * * 1,2,3,4,5,6'
        run: pip install -r ./requirements.txt && python ./weekup.py
      - name: github.event.schedule == '0 8 * * 1,2,3,4,5,6'
        run: pip install -r ./requirements.txt && python ./morning_start.py
